Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never # Redmine is not compatible
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  # Enabled: false
