require:
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.1

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never # Redmine is not compatible
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
